name: Website green-o-meter

on:
  push:
    branches: main

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - run: npm i
      - name: green-website
        uses: filiptronicek/green-action@0.0.1
        env:
            URL: https://trnck.dev
